version: '3'

volumes:
  dbdata: 
  dbdata-slave1:
  dbdata-slave2:
  proxysql-data: 

services:

  mysql-amp:
    container_name: amplifydb
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: cacapoop
      MYSQL_DATABASE: amplifydb
      MYSQL_USER: amp
      MYSQL_PASSWORD: cacapoop

    restart: always
    volumes:
      - ./mysql/master/my1.cnf:/etc/mysql/my.cnf
      - ./mysql/master/data:/var/lib/mysql
      - ./mysql/master/init.sql:/docker-entrypoint-initdb.d/init.sql


    
  mysql-slave-amp1:
    container_name: amplifydb-slave1
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: cacapoop
      MYSQL_DATABASE: amplifydb
      MYSQL_USER: amp
      MYSQL_PASSWORD: cacapoop
    restart: always
    volumes:
      - ./mysql/slave/my1.cnf:/etc/mysql/my.cnf
      - ./mysql/slave/data:/var/lib/mysql
      - ./mysql/slave/init.sql:/docker-entrypoint-initdb.d/init.sql
    #command: sh "sqlSlaveInit.sh"
    
  proxysql:
    image: proxysql/proxysql
    container_name: proxysql
    ports:
      - 6032:6032
      - 6033:6033
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
    depends_on:
      - mysql-amp
      - mysql-slave-amp1
      - mysql-slave-amp2

  amplify-web-1:
    container_name: amplify-web-1
    image: dexaxi/amplify-docker:latest
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      DATABASE_LOAD: "true"
      
      INTERNALSERVICE_BASEURI: http://amplify-loadbalancer-internal:80

      SPRING_DATASOURCE_USERNAME: amp
      SPRING_DATASOURCE_PASSWORD: cacapoop
      SPRING_DATASOURCE_URL: jdbc:mysql://proxysql:6033/amplifydb

    restart: always
    depends_on:
      - amplifydb
      - proxysql
      - amplify-loadbalancer-internal
  
  amplify-web-2:
    container_name: amplify-web-2
    image: dexaxi/amplify-docker:latest
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      
      DATABASE_LOAD: "false"
      INTERNALSERVICE_BASEURI: http://amplify-loadbalancer-internal:80

      SPRING_DATASOURCE_USERNAME: amp
      SPRING_DATASOURCE_PASSWORD: cacapoop
      SPRING_DATASOURCE_URL: jdbc:mysql://proxysql:6033/amplifydb
    restart: always
    depends_on:
      - amplifydb
      - proxysql
      - amplify-loadbalancer-internal

  amplify-internal-1:
    container_name: amplify-internal-1
    image: dexaxi/amplify-internal:latest
    environment:

      SPRING_DATASOURCE_USERNAME: amp
      SPRING_DATASOURCE_PASSWORD: cacapoop
      SPRING_DATASOURCE_URL: jdbc:mysql://proxysql:6033/amplifydb
    restart: always
    depends_on:
      - amplifydb
      - proxysql

  amplify-internal-2:
    container_name: amplify-internal-2
    image: dexaxi/amplify-internal:latest
    environment:

      SPRING_DATASOURCE_USERNAME: amp
      SPRING_DATASOURCE_PASSWORD: cacapoop
      SPRING_DATASOURCE_URL: jdbc:mysql://proxysql:6033/amplifydb
    restart: always
    depends_on:
      - amplifydb
      - proxysql
  
  amplify-loadbalancer-web:
    container_name: amplify-loadbalancer-web
    build: ./haproxy-web
    restart: always
    ports: 
      - 443:443
    depends_on: 
    - amplify-web-1
    - amplify-web-2

  amplify-loadbalancer-internal:
    container_name: amplify-loadbalancer-internal
    build: ./haproxy-internal
    restart: always
    depends_on:
      - amplify-internal-1
      - amplify-internal-2