version: '3'

volumes:
  dbdata:

services:

  mysql-amp:
    container_name: amplifydb
    image: mysql:8.0.17
    env_file: ./Docker/master/.env.master
    ports:
      - "3306:3306"
    cap_add: 
      - all
    environment:
      MYSQL_ROOT_PASSWORD: cacapoop
      MYSQL_DATABASE: amplifydb
    
    volumes:
      - dbdata:/var/lib/mysql
      # This doesn't work  ¯\_(ツ)_/¯
      #- ./master/master_mysql_connector.sh:/tmp/master_mysql_connector.sh
    #command: /bin/bash -x /tmp/master_mysql_connector.sh
    networks:
      default:
        aliases:
          - mysql
    restart: always
    
  mysql-slave-amp:
    container_name: amplifydb-slave
    image: mysql:8.0.17
    env_file: ./Docker/slave/.env.slave
    ports:
      - "3307:3306"
    cap_add: 
     - all
    environment:
      MYSQL_ROOT_PASSWORD: cacapoop
    volumes:
      - .dbdata:/var/lib/mysql
      # ¯\_(ツ)_/¯
      #- ./slave/slave_mysql_connector.sh:/tmp/slave_mysql_connector.sh
      #command: /bin/bash -x /tmp/slave_mysql_connector.sh
    networks:
      default:
        aliases:
          - mysql
    restart: always

  proxysql:
    image: proxysql/proxysql
    container_name: proxysql
    ports:
      - 6032:6032
      - 6033:6033
    volumes:
      - ./prroxysql/proxysql.cnf:/etx/proxysql.cnf
      - ./proxysql/data://var/lib/proxysql
    networks:
      - mysql_cluster_net
    depends_on:
      - mysql-amp
      - mysql-slave-amp

  amplify-web-1:
    container_name: amplify-web-1
    image: dexaxi/amplify-docker:latest
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      DATABASE_LOAD: true
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-amp:3306/amplifydb
      INTERNALSERVICE_BASEURI: http://amplify-loadbalancer-internal:80
    restart: always
    depends_on:
      - amplifydb
      - amplify-loadbalancer-internal
  
  amplify-web-2:
    container_name: amplify-web-2
    image: dexaxi/amplify-docker:latest
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-amp:3306/amplifydb
      DATABASE_LOAD: false
      INTERNALSERVICE_BASEURI: http://amplify-loadbalancer-internal:80
    restart: always
    depends_on:
      - amplifydb
      - amplify-loadbalancer-internal
      - amplify-web-1

  amplify-internal-1:
    container_name: amplify-internal-1
    image: dexaxi/amplify-internal:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-amp:3306/amplifydb
    restart: always
    depends_on:
      - amplifydb

  amplify-internal-2:
    container_name: amplify-internal-2
    image: dexaxi/amplify-internal:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-amp:3306/amplifydb
    restart: always
    depends_on:
      - amplifydb
  
  amplify-loadbalancer-web:
    container_name: amplify-loadbalancer-web
    build: ./haproxy-web
    restart: always
    ports: 
      - 443:443
    depends_on: 
    - amplify-web-1
    - amplify-web-2

  amplify-loadbalancer-internal:
    container_name: amplify-loadbalancer-internal
    build: ./haproxy-internal
    restart: always
    depends_on:
      - amplify-internal-1
      - amplify-internal-2

networks:
  mysql_cluster_net:
    driver: bridge


